<?php

// HAWIKI config file for TikiWiki
// Last modified: 5. July 2003

define("HAWIKI_TITLE", "TikiWiki");       // -> "title" of created HAWHAW deck
define("HAWIKI_MAXINPUTCHARS", 100000);   // maximum wiki size
define("HAWIKI_DISP_WIDTH",  300);        // HAWHAW display width (pixel)
define("HAWIKI_DISP_HEIGHT", 300);        //                height
define("HAWIKI_DISP_BGCOLOR", "#00BB77"); //                background color

// error messages (modify these string for country adaptions
define("HAWIKI_ERROR", "Error:");
define("HAWIKI_ERROR_INVWIKISIZE", "Invalid wiki size");
define("HAWIKI_ERROR_INVWIKISYNTAX", "Invalid wiki syntax");

?>