<?php
/**
 * interface for an Error_Handler
 *
 * @package   Tiki
 * @subpackage
 * @copyright (c) Copyright 2002-2013 by authors of the Tiki Wiki CMS Groupware Project. All Rights Reserved. See copyright.txt for details and a complete list of authors.
 * @license   LGPL. See license.txt for more details
 */
// $Id$


/**
 * describes the function used to handle Database Errors
 * @package Tiki\Core\TikiDb
 */
interface TikiDb_ErrorHandler
{
	/**
	 * should handle any errors generated by $query
	 * @param TikiDb $db
	 * @param        $query
	 * @param        $values
	 * @param        $result
	 *
	 * @return mixed
	 */
	function handle( TikiDb $db, $query, $values, $result );
}
