<?php // -*- coding:utf-8 -*- $Id: /cvsroot/tikiwiki/tiki/img/flags/flagnames.php,v 1.10 2007-03-02 19:49:20 luciash Exp $
/* 
 * The listing associates country names used as filenames for flags in Tikiwiki for language translation
 */

// This script is only for language translations - so its better to die if called directly.
if (strpos($_SERVER["SCRIPT_NAME"],basename(__FILE__)) !== false) {
  header("location: index.php");
	exit;
}

// Here come the dynamically generated strings for img/flags/*.gif
tra('Andorra');
tra('United Arab Emirates');
tra('United Nations Organization');
tra('Afghanistan');
tra('Antigua');
tra('Anguilla');
tra('Albania');
tra('Armenia');
tra('Netherlands Antilles');
tra('Angola');
tra('Antarctica');
tra('Argentina');
tra('American Samoa');
tra('Austria');
tra('Australia');
tra('Aruba');
tra('Aland Islands');
tra('Azerbaijan');
tra('Bosnia and Herzegovina');
tra('Barbados');
tra('Bangladesh');
tra('Belgium');
tra('Burkina Faso');
tra('Bulgaria');
tra('Bahrain');
tra('Burundi');
tra('Benin');
tra('Bermuda');
tra('Brunei');
tra('Bolivia');
tra('Brazil');
tra('Bahamas');
tra('Bhutan');
tra('Bouvet Island');
tra('Botswana');
tra('Belarus');
tra('Belize');
tra('Canada');
tra('Catalan Countries');
tra('Cocos Islands');
tra('Central African Republic');
tra('Congo Democratic');
tra('Congo');
tra('Switzerland');
tra('Ivory Coast');
tra('Cook Islands');
tra('Chile');
tra('Cameroon');
tra('China');
tra('Colombia');
tra('Costa Rica');
tra('Cuba');
tra('Cape Verde');
tra('Christmas Island');
tra('Cyprus');
tra('Czech Republic');
tra('Germany');
tra('Djibouti');
tra('Denmark');
tra('Dominica');
tra('Dominican Republic');
tra('Algeria');
tra('Ecuador');
tra('Estonia');
tra('Egypt');
tra('Western Sahara');
tra('Eritrea');
tra('Spain');
tra('Ethiopia');
tra('Finland');
tra('Fiji');
tra('Falkland Islands');
tra('Federated States of Micronesia');
tra('Faroe Islands');
tra('France');
tra('Gabon');
tra('United Kingdom');
tra('Grenada');
tra('Georgia');
tra('French Guiana');
tra('Guernsey');
tra('Ghana');
tra('Gibraltar');
tra('Greenland');
tra('Gambia');
tra('Guinea');
tra('Guadeloupe');
tra('Equatorial Guinea');
tra('Greece');
tra('South Georgia and South Sandwich Islands');
tra('Guatemala');
tra('Guam');
tra('Guinea Bissau');
tra('Guyana');
tra('Hong Kong');
tra('Heard Island and McDonald Islands');
tra('Honduras');
tra('Croatia');
tra('Haiti');
tra('Hungary');
tra('Indonesia');
tra('Ireland');
tra('Israel');
tra('Isle of Man');
tra('India');
tra('British Indian Ocean Territory');
tra('Iraq');
tra('Iran');
tra('Iceland');
tra('Italy');
tra('Jersey');
tra('Jamaica');
tra('Jordan');
tra('Japan');
tra('Kenya');
tra('Kyrgyzstan');
tra('Cambodia');
tra('Kiribati');
tra('Comoros');
tra('Saint Kitts and Nevis');
tra('North Korea');
tra('South Korea');
tra('Kuwait');
tra('Cayman Islands');
tra('Kazakstan');
tra('Laos');
tra('Lebanon');
tra('Saint Lucia');
tra('Liechtenstein');
tra('Sri Lanka');
tra('Liberia');
tra('Lesotho');
tra('Lithuania');
tra('Luxemburg');
tra('Latvia');
tra('Libya');
tra('Morocco');
tra('Monaco');
tra('Moldova');
tra('Montenegro');
tra('Madagascar');
tra('Marshall Islands');
tra('Macedonia');
tra('Mali');
tra('Myanmar');
tra('Mongolia');
tra('Macao');
tra('Northern Mariana Islands');
tra('Martinique');
tra('Mauritania');
tra('Montserrat');
tra('Malta');
tra('Mauritius');
tra('Maldives');
tra('Malawi');
tra('Mexico');
tra('Malaysia');
tra('Mozambique');
tra('Namibia');
tra('New Caledonia');
tra('Niger');
tra('Norfolk Island');
tra('Nigeria');
tra('Nicaragua');
tra('Netherlands');
tra('Norway');
tra('Nepal');
tra('Nauru');
tra('Niue');
tra('New Zealand');
tra('Oman');
tra('Panama');
tra('Peru');
tra('French Polynesia');
tra('Papua New Guinea');
tra('Phillippines');
tra('Pakistan');
tra('Poland');
tra('Saint Pierre and Miquelon');
tra('Pitcairn');
tra('Puerto Rico');
tra('Palestine');
tra('Portugal');
tra('Palau');
tra('Paraguay');
tra('Quatar');
tra('Reunion');
tra('Romania');
tra('Serbia');
tra('Russia');
tra('Rwanda');
tra('Saudi Arabia');
tra('Solomon Islands');
tra('Seychelles');
tra('Sudan');
tra('Sweden');
tra('Singapore');
tra('Saint Helena');
tra('Slovenia');
tra('Svalbard and Jan Mayen');
tra('Slovakia');
tra('Sierra Leone');
tra('San Marino');
tra('Senegal');
tra('Somalia');
tra('Surinam');
tra('Sao Tome and Principe');
tra('El Salvador');
tra('Syria');
tra('Swaziland');
tra('Turks and Caicos Islands');
tra('Chad');
tra('French Southern Territories');
tra('Togo');
tra('Thailand');
tra('Tajikistan');
tra('Tokelau');
tra('Timor-Leste');
tra('Turkmenistan');
tra('Tunisia');
tra('Tonga');
tra('Turkey');
tra('Trinidad Tobago');
tra('Tuvalu');
tra('Taiwan');
tra('Tanzania');
tra('Ukraine');
tra('Uganda');
tra('United States Minor Outlying Islands');
tra('United States');
tra('Uruguay');
tra('Uzbekistan');
tra('Vatican');
tra('St Vincent Grenadines');
tra('Venezuela');
tra('British Virgin Islands');
tra('US Virgin Islands');
tra('Viet Nam');
tra('Vanuatu');
tra('Wales');
tra('Wallis and Futuna');
tra('World');
tra('Samoa');
tra('Yemen');
tra('Mayotte');
tra('South Africa');
tra('Zambia');
tra('Zimbabwe');
tra('Europe');
tra('Yugoslavia');
?>
