--  jonnyb: remove tables no longer used in tiki 4
DROP TABLE `galaxia_activities`,
           `galaxia_activity_roles`,
           `galaxia_instances`, 
           `galaxia_instance_activities`, 
           `galaxia_instance_comments`, 
           `galaxia_processes`, 
           `galaxia_roles`, 
           `galaxia_transitions`, 
           `galaxia_user_roles`, 
           `galaxia_workitems`, 
           `tiki_charts`, 
           `tiki_charts_rankings`, 
           `tiki_charts_votes`, 
           `tiki_chart_items`, 
           `tiki_drawings`, 
           `tiki_newsreader_marks`, 
           `tiki_newsreader_servers`, 
           `tiki_quicktags`;
