<?php

function prefs_socialnetworks_list() {
	return array(
		'socialnetworks_twitter_consumer_key' => array(
			'name' => tra('Consumer key'),
			'description' => tra('Consumer key generated by registering your site as application at twitter'),
			'type' => 'text',
			'keywords' => 'social networks',
			'size' => 40,
		),
		'socialnetworks_twitter_consumer_secret' => array(
			'name' => tra('Consumer secret'),
			'description' => tra('Consumer secret generated by registering your site as an application at twitter'),
			'keywords' => 'social networks',
			'type' => 'text',
			'size' => 60,
			'filter' => 'description',
		),
	);
}
