Instance Class Reference
Public Member Functions
Instance ($db)
getInstance ($instanceId)
setNextActivity ($actname)
setNextUser ($user)
set ($name,$value)
get ($name)
getActivities ()
getStatus ()
setStatus ($status)
getInstanceId ()
getProcessId ()
getOwner ()
setOwner ($user)
setActivityUser ($activityId,$theuser)
getActivityUser ($activityId)
setActivityStatus ($activityId,$status)
getActivityStatus ($activityId)
setActivityStarted ($activityId)
getActivityStarted ($activityId)
setStarted ($time)
getStarted ()
setEnded ($time)
getEnded ()
complete ($activityId=0,$force=false,$addworkitem=true)
terminate ()
sendTo ($from,$activityId,$split=false)
get_instance_comment ($cId)
replace_instance_comment ($cId,$activityId,$activity,$user,$title,$comment)
remove_instance_comment ($cId)
get_instance_comments ()
Public Attributes
properties = Array()
owner = ''
status = ''
started
nextActivity
nextUser
ended
activities = Array()
Array of asocs(activityId,status,started,user).
pId
instanceId = 0
workitems = Array()
An array of workitem ids.
Detailed Description
This class represents a process instance, it is used when any activity is executed. The $instance object is created representing the instance of a process being executed in the activity or even a to-be-created instance if the activity is a start activity.
Definition at line 10 of file Instance.php.
Member Function Documentation
Instance::complete ($ activityId = 0, $ force = false, $ addworkitem = true)
Completes an activity, normally from any activity you should call this function without arguments. The arguments are explained just in case. $activityId is the activity that is being completed, when this is not passed the engine takes it from the $_REQUEST array,all activities are executed passing the activityId in the URI. $force indicates that the instance must be routed no matter if the activity is auto-routing or not. This is used when `sending` an instance from a non-auto-routed activity to the next activity. $addworkitem indicates if a workitem should be added for the completed activity. YOU MUST NOT CALL complete() for non-interactive activities since the engine does automatically complete automatic activities after executing them.
Definition at line 384 of file Instance.php.
References getOwner(), getStarted(), sendTo(), setActivityStatus(), and terminate().
Referenced by sendTo().
Instance::get ($ name)
Gets the value of an instance property.
Definition at line 150 of file Instance.php.
Instance::get_instance_comment ($ cId)
Gets a comment for this instance
Definition at line 610 of file Instance.php.
Instance::get_instance_comments ()
Lists instance comments
Definition at line 662 of file Instance.php.
Instance::getActivities ()
Returns an array of asocs describing the activities where the instance is present, can be more than one activity if the instance was `splitted`
Definition at line 163 of file Instance.php.
Instance::getActivityStarted ($ activityId)
Gets the Unix timstamp of the starting time for the given activity.
Definition at line 306 of file Instance.php.
Instance::getActivityStatus ($ activityId)
Gets the status of the instance in some activity, can be 'running' or 'completed'
Definition at line 278 of file Instance.php.
Instance::getActivityUser ($ activityId)
Returns the user that must execute or is already executing an activity wherethis instance is present.
Definition at line 248 of file Instance.php.
Instance::getEnded ()
Gets the end time of the instance (when the process was completed)
Definition at line 361 of file Instance.php.
Instance::getInstance ($ instanceId)
Method used to load an instance data from the database.
Definition at line 33 of file Instance.php.
Referenced by sendTo().
Instance::getInstanceId ()
Returns the instanceId
Definition at line 193 of file Instance.php.
Instance::getOwner ()
Returns the user that created the instance
Definition at line 209 of file Instance.php.
Referenced by complete().
Instance::getProcessId ()
Returns the processId for this instance
Definition at line 201 of file Instance.php.
Instance::getStarted ()
Gets the time where the instance was started (Unix timestamp)
Definition at line 343 of file Instance.php.
Referenced by complete().
Instance::getStatus ()
Gets the instance status can be 'completed', 'active', 'aborted' or 'exception'
Definition at line 172 of file Instance.php.
Instance::remove_instance_comment ($ cId)
Removes an instance comment
Definition at line 652 of file Instance.php.
Instance::replace_instance_comment ($ cId, $ activityId, $ activity, $ user, $ title, $ comment)
Inserts or updates an instance comment
Definition at line 623 of file Instance.php.
Instance::sendTo ($ from, $ activityId, $ split = false)
Sends the instance from some activity to another activity. You should not call this method unless you know very very well what you are doing.
Definition at line 504 of file Instance.php.
References complete(), and getInstance().
Referenced by complete().
Instance::set ($ name, $ value)
Sets a property in this instance. This method is used in activities to set instance properties. Instance properties are inemdiately serialized.
Definition at line 139 of file Instance.php.
Instance::setActivityStarted ($ activityId)
Resets the start time of the activity indicated to the current time.
Definition at line 291 of file Instance.php.
Instance::setActivityStatus ($ activityId, $ status)
Sets the status of the instance in some activity, can be 'running' or 'completed'
Definition at line 262 of file Instance.php.
Referenced by complete().
Instance::setActivityUser ($ activityId, $ theuser)
Sets the user that must execute the activity indicated by the activityId. Note that the instance MUST be present in the activity to set the user, you can't program who will execute an activity.
Definition at line 231 of file Instance.php.
Instance::setEnded ($ time)
Sets the end time of the instance (when the process was completed)
Definition at line 351 of file Instance.php.
Instance::setNextActivity ($ actname)
Sets the next activity to be executed, if the current activity is a switch activity the complete() method will use the activity setted in this method as the next activity for the instance. Note that this method receives an activity name as argument. (Not an Id)
Definition at line 66 of file Instance.php.
Instance::setNextUser ($ user)
This method can be used to set the user that must perform the next activity of the process. this effectively `assigns` the instance to some user.
Definition at line 84 of file Instance.php.
Instance::setOwner ($ user)
Sets the instance creator user
Definition at line 217 of file Instance.php.
Instance::setStarted ($ time)
Sets the time where the instance was started.
Definition at line 333 of file Instance.php.
Instance::setStatus ($ status)
Sets the instance status , the value can be: 'completed', 'active', 'aborted' or 'exception'
Definition at line 181 of file Instance.php.
Instance::terminate ()
Terminates the instance marking the instance and the process as completed. This is the end of a process. Normally you should not call this method since it is automatically called when an end activity is completed.
Definition at line 486 of file Instance.php.
Referenced by complete().
The documentation for this class was generated from the following file:
Instance.php