<?php
// (c) Copyright 2002-2011 by authors of the Tiki Wiki CMS Groupware Project
//
// All Rights Reserved. See copyright.txt for details and a complete list of authors.
// Licensed under the GNU LESSER GENERAL PUBLIC LICENSE. See license.txt for details.
// $Id$

/**
 * Test class for TikiConnect.
 * Generated by PHPUnit on 2011-08-24 at 13:32:56.
 */
class TikiConnectTest extends TikiTestCase
{
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->obj = new TikiConnect;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	public function testBuildConnectData()
	{
		$data = $this->obj->buildConnectData(); // TODO check status etc

		$this->assertGreaterThan(0, count($data));
	}

	/**
	 * @todo Implement testRecordConnection().
	 */
	public function testRecordConnection()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLastDataSent().
	 */
	public function testGetLastDataSent()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDiffDataWithLastSent().
	 */
	public function testDiffDataWithLastSent()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetPendingGuid().
	 */
	public function testGetPendingGuid()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetConfirmedGuid().
	 */
	public function testGetConfirmedGuid()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsPendingGuid().
	 */
	public function testIsPendingGuid()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsConfirmedGuid().
	 */
	public function testIsConfirmedGuid()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}

?>
