{remarksbox type="tip" title="{tr}Tip{/tr}"}
	{tr}Use this page to configure the feeds generated by Tiki. To syndicate feeds from other sites, use the <strong>Admin</strong> &gt; <strong>External Feeds</strong> menu option, or{/tr} <a class="rbox-link" href="tiki-admin_rssmodules.php" title="{tr}External feeds{/tr}">{tr}Click Here{/tr}</a>.
{/remarksbox}

<form action="tiki-admin.php?page=rss" method="post">
	<input type="hidden" name="rss" />
	<div class="heading input_submit_container" style="text-align: right">
		<input type="submit" value="{tr}Change preferences{/tr}" />
	</div>

	{tabset name="admin_rss"}
		{tab name="{tr}General Preferences{/tr}"}
			{preference name=rssfeed_default_version}
			<em>
				{tr}Specification{/tr}
				<a href="http://www.w3.org/TR/rdf-schema/" target="tikihelp" class="tikihelp" title="{tr}Specification:{/tr} RDF 1.0">RDF 1.0</a>,
				<a href="http://blogs.law.harvard.edu/tech/rss" target="tikihelp" class="tikihelp" title="{tr}Specification:{/tr} RDF 2.0">RDF 2.0</a>,
				<a href="http://bitworking.org/rfc/draft-gregorio-07.html" target="tikihelp" class="tikihelp" title="{tr}Specification:{/tr} Atom 0.3">Atom 0.3</a>.
			</em>

			{preference name=rssfeed_language}
			{preference name=rssfeed_editor}
			{preference name=rssfeed_webmaster}
			{preference name=rssfeed_img}
			{preference name=rss_cache_time}

			{remarksbox type="Note" title="{tr}Note{/tr}"}
				{tr}Enabling caching will override existing permissions - all content will be public. Enable this option <strong>only</strong> if your syndicated content should be public.{/tr}
			{/remarksbox}	
				
			{preference name=rss_basic_auth}
		{/tab}

		{tab name="{tr}Feeds{/tr}"}

			{preference name=rss_articles}
			<div class="adminoptionboxchild" id="rss_articles_childcontainer">
				<a href="tiki-articles_rss.php" title="{tr}Feed for articles{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_articles}
				{preference name=desc_rss_articles}
				{preference name=max_rss_articles}
				{preference name=showAuthor_rss_articles}
				{preference name=index_rss_articles}
			</div>

			{preference name=rss_blogs}
			<div class="adminoptionboxchild" id="rss_blogs_childcontainer">
				<a href="tiki-blogs_rss.php" title="{tr}Feed for blogs{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_blogs}
				{preference name=desc_rss_blogs}
				{preference name=max_rss_blogs}
				{preference name=showAuthor_rss_blogs}
				{preference name=index_rss_blogs}
			</div>

			{preference name=rss_blog}
			<div class="adminoptionboxchild" id="rss_blog_childcontainer">
				<a href="tiki-blog_rss.php" title="{tr}Feed for individual blogs{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_blog}
				{preference name=desc_rss_blog}
				{preference name=max_rss_blog}
				{preference name=showAuthor_rss_blog}
				{preference name=index_rss_blog}
			</div>

			{preference name=rss_image_galleries}
			<div class="adminoptionboxchild" id="rss_image_galleries_childcontainer">
				<a href="tiki-image_galleries_rss.php" title="{tr}Feed for image galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_image_galleries}
				{preference name=desc_rss_image_galleries}
				{preference name=max_rss_image_galleries}
				{preference name=showAuthor_rss_image_galleries}
				{preference name=index_rss_image_galleries}
			</div>

			{preference name=rss_image_gallery}
			<div class="adminoptionboxchild" id="rss_image_gallery_childcontainer">
				<a href="tiki-image_gallery_rss.php" title="{tr}Feed for individual image galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_image_gallery}
				{preference name=desc_rss_image_gallery}
				{preference name=max_rss_image_gallery}
				{preference name=showAuthor_rss_image_gallery}
				{preference name=index_rss_image_gallery}
			</div>

			{preference name=rss_file_galleries}
			<div class="adminoptionboxchild" id="rss_file_galleries_childcontainer">
				<a href="tiki-file_galleries_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_file_galleries}
				{preference name=desc_rss_file_galleries}
				{preference name=max_rss_file_galleries}
				{preference name=showAuthor_rss_file_galleries}
				{preference name=index_rss_file_galleries}
			</div>

			{preference name=rss_file_gallery}
			<div class="adminoptionboxchild" id="rss_file_gallery_childcontainer">
				<a href="tiki-file_gallery_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_file_gallery}
				{preference name=desc_rss_file_gallery}
				{preference name=max_rss_file_gallery}
				{preference name=showAuthor_rss_file_gallery}
				{preference name=index_rss_file_gallery}
			</div>

			{preference name=rss_wiki}
			<div class="adminoptionboxchild" id="rss_wiki_childcontainer">
				<a href="tiki-wiki_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_wiki}
				{preference name=desc_rss_wiki}
				{preference name=max_rss_wiki}
				{preference name=showAuthor_rss_wiki}
				{preference name=index_rss_wiki}
			</div>

			{preference name=rss_forums}
			<div class="adminoptionboxchild" id="rss_forums_childcontainer">
				<a href="tiki-forums_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_forums}
				{preference name=desc_rss_forums}
				{preference name=max_rss_forums}
				{preference name=showAuthor_rss_forums}
				{preference name=index_rss_forums}
			</div>
			
			{preference name=rss_forum}
			<div class="adminoptionboxchild" id="rss_forum_childcontainer">
				<a href="tiki-forum_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_forum}
				{preference name=desc_rss_forum}
				{preference name=max_rss_forum}
				{preference name=showAuthor_rss_forum}
				{preference name=index_rss_forum}
			</div>

			{preference name=rss_trackers}
			<div class="adminoptionboxchild" id="rss_trackers_childcontainer">
				<a href="tiki-trackers_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_trackers}
				{preference name=desc_rss_trackers}
				{preference name=max_rss_trackers}
				{preference name=showAuthor_rss_trackers}
				{preference name=index_rss_trackers}
			</div>

			{preference name=rss_tracker}
			<div class="adminoptionboxchild" id="rss_tracker_childcontainer">
				<a href="tiki-tracker_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_tracker}
				{preference name=desc_rss_tracker}
				{preference name=max_rss_tracker}
				{preference name=showAuthor_rss_tracker}
				{preference name=index_rss_tracker}
			</div>

			{preference name=rss_calendar}
			<div class="adminoptionboxchild" id="rss_calendar_childcontainer">
				<a href="tiki-calendar_rss.php" title="{tr}Feed for file galleries{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_calendar}
				{preference name=desc_rss_calendar}
				{preference name=max_rss_calendar}
				{preference name=showAuthor_rss_calendar}
				{preference name=index_rss_calendar}
			</div>
			
			{preference name=rss_directories}
			<div class="adminoptionboxchild" id="rss_directories_childcontainer">
				<a href="tiki-directories_rss.php" title="{tr}Feed for directories{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_directories}
				{preference name=desc_rss_directories}
				{preference name=max_rss_directories}
				{preference name=showAuthor_rss_directories}
				{preference name=index_rss_directories}
			</div>

			{preference name=rss_maps}
			<div class="adminoptionboxchild" id="rss_maps_childcontainer">
				<a href="tiki-maps_rss.php" title="{tr}Feed for maps{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_maps}
				{preference name=desc_rss_maps}
				{preference name=max_rss_maps}
				{preference name=showAuthor_rss_maps}
				{preference name=index_rss_maps}
			</div>

			{preference name=rss_shoutbox}
			<div class="adminoptionboxchild" id="rss_shoutbox_childcontainer">
				<a href="tiki-maps_rss.php" title="{tr}Feed for shoutbox{/tr}."> {icon _id=feed}</a>
				{preference name=title_rss_shoutbox}
				{preference name=desc_rss_shoutbox}
				{preference name=max_rss_shoutbox}
				{preference name=showAuthor_rss_shoutbox}
				{preference name=index_rss_shoutbox}
			</div>
		{/tab}
	{/tabset}

	<div class="heading input_submit_container" style="text-align: center">
		<input type="submit" value="{tr}Change preferences{/tr}" />
	</div>
</form>
