BaseActivity Class Reference
Public Member Functions
setDb ($db)
BaseActivity ($db)
getActivity ($activityId)
getUserRoles ($user)
getActivityRoleNames ()
getNormalizedName ()
setNormalizedName ($name)
setName ($name)
getName ()
setDescription ($desc)
getDescription ()
setIsInteractive ($is)
isInteractive ()
setIsAutoRouted ($is)
isAutoRouted ()
setProcessId ($pid)
getProcessId ()
getActivityId ()
setActivityId ($id)
getRoles ()
setRoles ($roles)
Public Attributes
$name
$normalizedName
$description
$isInteractive
$isAutoRouted
$roles = Array()
$outbound = Array()
$inbound = Array()
$pId
$activityId
Detailed Description
This class represents activities, and must be derived for each activity type supported in the system. Derived activities extending this class can be found in the activities subfolder. This class is observable.
Definition at line 11 of file BaseActivity.php.
Member Function Documentation
BaseActivity::getActivity ($ activityId)
Factory method returning an activity of the desired type loading the information from the database.
Definition at line 38 of file BaseActivity.php.
References isAutoRouted(), and isInteractive().
BaseActivity::getActivityId ()
Gets the activityId
Definition at line 177 of file BaseActivity.php.
BaseActivity::getActivityRoleNames ()
Returns an Array of asociative arrays with roleId and name for the given user
Definition at line 105 of file BaseActivity.php.
BaseActivity::getDescription ()
Gets the activity description
Definition at line 142 of file BaseActivity.php.
BaseActivity::getName ()
Gets the activity name
Definition at line 132 of file BaseActivity.php.
BaseActivity::getNormalizedName ()
Returns the normalized name for the activity
Definition at line 117 of file BaseActivity.php.
BaseActivity::getProcessId ()
Gets the processId for this activity
Definition at line 172 of file BaseActivity.php.
BaseActivity::getRoles ()
Gets array with roleIds asociated to this activity
Definition at line 187 of file BaseActivity.php.
BaseActivity::getUserRoles ($ user)
Returns an Array of roleIds for the given user
Definition at line 93 of file BaseActivity.php.
BaseActivity::isAutoRouted ()
Gets if the activity is auto routed
Definition at line 162 of file BaseActivity.php.
Referenced by getActivity().
BaseActivity::isInteractive ()
Returns if the activity is interactive
Definition at line 152 of file BaseActivity.php.
Referenced by getActivity().
BaseActivity::setActivityId ($ id)
Sets the activityId
Definition at line 182 of file BaseActivity.php.
BaseActivity::setDescription ($ desc)
Sets the activity description
Definition at line 137 of file BaseActivity.php.
BaseActivity::setIsAutoRouted ($ is)
Sets if the activity is auto-routed
Definition at line 157 of file BaseActivity.php.
BaseActivity::setIsInteractive ($ is)
Sets if the activity is interactive
Definition at line 147 of file BaseActivity.php.
BaseActivity::setName ($ name)
Sets the name for the activity
Definition at line 127 of file BaseActivity.php.
BaseActivity::setNormalizedName ($ name)
Sets normalized name for the activity
Definition at line 122 of file BaseActivity.php.
BaseActivity::setProcessId ($ pid)
Sets the processId for this activity
Definition at line 167 of file BaseActivity.php.
BaseActivity::setRoles ($ roles)
Sets roles for this activities, shoule receive an array of roleIds
Definition at line 193 of file BaseActivity.php.
The documentation for this class was generated from the following file:
BaseActivity.php