ActivityManager Class Reference
Public Member Functions
ActivityManager ($db)
get_error ()
add_activity_role ($activityId,$roleId)
get_activity_roles ($activityId)
remove_activity_role ($activityId,$roleId)
transition_exists ($pid,$actFromId,$actToId)
add_transition ($pId,$actFromId,$actToId)
remove_transition ($actFromId,$actToId)
remove_activity_transitions ($pId,$aid)
get_process_transitions ($pId,$actid=0)
activity_is_auto_routed ($actid)
get_process_activities ($pId)
build_process_graph ($pId)
validate_process_activities ($pId)
validate_process_sources ($pid)
activity_name_exists ($pId,$name)
get_activity ($pId,$activityId)
list_activities ($pId,$offset,$maxRecords,$sort_mode,$find,$where='')
remove_activity ($pId,$activityId)
replace_activity ($pId,$activityId,$vars)
Public Attributes
error = ''
return activityId
Detailed Description
This class is used to add,remove,modify and list activities used in the Workflow engine. Activities are managed in a per-process level, each activity belongs to some process.
Definition at line 12 of file ActivityManager.php.
Constructor & Destructor Documentation
ActivityManager::ActivityManager ($ db)
Constructor takes a PEAR::Db object to be used to manipulate activities in the database.
Definition at line 19 of file ActivityManager.php.
Member Function Documentation
ActivityManager::activity_is_auto_routed ($ actid)
Indicates if an activity is autoRouted
Definition at line 148 of file ActivityManager.php.
ActivityManager::activity_name_exists ($ pId, $ name)
Indicates if an activity with the same name exists
Definition at line 403 of file ActivityManager.php.
Referenced by replace_activity().
ActivityManager::add_activity_role ($ activityId, $ roleId)
Asociates an activity with a role
Definition at line 35 of file ActivityManager.php.
ActivityManager::add_transition ($ pId, $ actFromId, $ actToId)
Adds a transition
Definition at line 76 of file ActivityManager.php.
References get_activity().
ActivityManager::build_process_graph ($ pId)
Builds the graph
Definition at line 172 of file ActivityManager.php.
References get_process_activities(), and get_process_transitions().
ActivityManager::get_activity ($ pId, $ activityId)
Gets a activity fields are returned as an asociative array
Definition at line 413 of file ActivityManager.php.
Referenced by add_transition().
ActivityManager::get_activity_roles ($ activityId)
Gets the roles asociated to an activity
Definition at line 45 of file ActivityManager.php.
ActivityManager::get_process_activities ($ pId)
Returns all the activities for a process as an array
Definition at line 157 of file ActivityManager.php.
Referenced by build_process_graph().
ActivityManager::get_process_transitions ($ pId, $ actid = 0)
Returns all the transitions for a process
Definition at line 130 of file ActivityManager.php.
Referenced by build_process_graph().
ActivityManager::list_activities ($ pId, $ offset, $ maxRecords, $ sort_mode, $ find, $ where = '')
Lists activities at a per-process level
Definition at line 424 of file ActivityManager.php.
ActivityManager::remove_activity ($ pId, $ activityId)
Removes a activity.
Definition at line 455 of file ActivityManager.php.
References remove_transition().
ActivityManager::remove_activity_role ($ activityId, $ roleId)
Removes a role from an activity
Definition at line 59 of file ActivityManager.php.
ActivityManager::remove_activity_transitions ($ pId, $ aid)
Removes all the activity transitions
Definition at line 120 of file ActivityManager.php.
ActivityManager::remove_transition ($ actFromId, $ actToId)
Removes a transition
Definition at line 110 of file ActivityManager.php.
Referenced by remove_activity().
ActivityManager::replace_activity ($ pId, $ activityId, $ vars)
Updates or inserts a new activity in the database, $vars is an asociative array containing the fields to update or to insert as needed. $pId is the processId $activityId is the activityId
Definition at line 484 of file ActivityManager.php.
References activity_name_exists().
ActivityManager::transition_exists ($ pid, $ actFromId, $ actToId)
Checks if a transition exists
Definition at line 68 of file ActivityManager.php.
ActivityManager::validate_process_activities ($ pId)
Validates if a process can be activated checking the process activities and transitions the rules are: 0) No circular activities 1) Must have only one a start and end activity 2) End must be reachable from start 3) Interactive activities must have a role assigned 4) Roles should be mapped 5) Standalone activities cannot have transitions 6) Non intractive activities non-auto routed must have some role so the user can `send` the activity
Definition at line 236 of file ActivityManager.php.
References validate_process_sources().
ActivityManager::validate_process_sources ($ pid)
Validate process sources Rules: 1) Interactive activities (non-standalone) must use complete() 2) Standalone activities must not use $instance 3) Switch activities must use setNextActivity 4) Non-interactive activities cannot use complete()
Definition at line 361 of file ActivityManager.php.
Referenced by validate_process_activities().
The documentation for this class was generated from the following file:
ActivityManager.php