ProcessManager Class Reference
Public Member Functions
ProcessManager ($db)
activate_process ($pId)
deactivate_process ($pId)
new_process_version ($pId,$minor=true)
process_name_exists ($name,$version)
get_process ($pId)
list_processes ($offset,$maxRecords,$sort_mode,$find,$where='')
remove_process ($pId)
replace_process ($pId,$vars)
_rec_copy ($dir1,$dir2)
ProcessManager ($db)
activate_process ($pId)
deactivate_process ($pId)
serialize_process ($pId)
unserialize_process ($xml)
import_process ($data)
new_process_version ($pId,$minor=true)
process_name_exists ($name,$version)
get_process ($pId)
list_processes ($offset,$maxRecords,$sort_mode,$find,$where='')
remove_process ($pId)
replace_process ($pId,$vars)
_rec_copy ($dir1,$dir2)
_start_element_handler ($parser,$element,$attribs)
_end_element_handler ($parser,$element)
_data_handler ($parser,$data)
Public Attributes
parser
tree
current
buffer
Detailed Description
This class is used to add,remove,modify and list processes.
Definition at line 10 of file ProcessManager/ProcessManager.php.
Constructor & Destructor Documentation
ProcessManager::ProcessManager ($ db)
Constructor takes a PEAR::Db object to be used to manipulate roles in the database.
Definition at line 16 of file ProcessManager/ProcessManager.php.
ProcessManager::ProcessManager ($ db)
Constructor takes a PEAR::Db object to be used to manipulate roles in the database.
Definition at line 20 of file src/ProcessManager/ProcessManager.php.
Member Function Documentation
ProcessManager::activate_process ($ pId)
Sets a process as active
Definition at line 32 of file src/ProcessManager/ProcessManager.php.
ProcessManager::activate_process ($ pId)
Sets a process as active
Definition at line 28 of file ProcessManager/ProcessManager.php.
ProcessManager::deactivate_process ($ pId)
De-activates a process
Definition at line 41 of file src/ProcessManager/ProcessManager.php.
ProcessManager::deactivate_process ($ pId)
De-activates a process
Definition at line 37 of file ProcessManager/ProcessManager.php.
ProcessManager::get_process ($ pId)
Gets a process by pId. Fields are returned as an asociative array
Definition at line 343 of file src/ProcessManager/ProcessManager.php.
ProcessManager::get_process ($ pId)
Gets a process by pId. Fields are returned as an asociative array
Definition at line 102 of file ProcessManager/ProcessManager.php.
Referenced by import_process(), new_process_version(), replace_process(), and serialize_process().
ProcessManager::import_process ($ data)
Creates a process from the process data structure, if you want to convert an XML to a process then use first unserialize_process and then this method.
Definition at line 217 of file src/ProcessManager/ProcessManager.php.
References get_process(), and replace_process().
ProcessManager::list_processes ($ offset, $ maxRecords, $ sort_mode, $ find, $ where = '')
Lists processes (all processes)
Definition at line 355 of file src/ProcessManager/ProcessManager.php.
ProcessManager::list_processes ($ offset, $ maxRecords, $ sort_mode, $ find, $ where = '')
Lists processes (all processes)
Definition at line 114 of file ProcessManager/ProcessManager.php.
ProcessManager::new_process_version ($ pId, $ minor = true)
Creates a new process based on an existing process changing the process version. By default the process is created as an unactive process and the version is by default a minor version of the process.
Todo copy process activities and so
Definition at line 291 of file src/ProcessManager/ProcessManager.php.
References get_process(), and replace_process().
ProcessManager::new_process_version ($ pId, $ minor = true)
Creates a new process based on an existing process changing the process version. By default the process is created as an unactive process and the version is by default a minor version of the process.
Todo copy process activities and so
Definition at line 50 of file ProcessManager/ProcessManager.php.
References get_process(), and replace_process().
ProcessManager::process_name_exists ($ name, $ version)
This function can be used to check if a process name exists, note that this is NOT used by replace_process since that function can be used to create new versions of an existing process. The application must use this method to ensure that processes have unique names.
Definition at line 333 of file src/ProcessManager/ProcessManager.php.
ProcessManager::process_name_exists ($ name, $ version)
This function can be used to check if a process name exists, note that this is NOT used by replace_process since that function can be used to create new versions of an existing process. The application must use this method to ensure that processes have unique names.
Definition at line 92 of file ProcessManager/ProcessManager.php.
ProcessManager::remove_process ($ pId)
Removes a process by pId
Definition at line 387 of file src/ProcessManager/ProcessManager.php.
ProcessManager::remove_process ($ pId)
Removes a process by pId
Definition at line 146 of file ProcessManager/ProcessManager.php.
ProcessManager::replace_process ($ pId, $ vars)
Updates or inserts a new process in the database, $vars is an asociative array containing the fields to update or to insert as needed. $pId is the processId
Definition at line 420 of file src/ProcessManager/ProcessManager.php.
References get_process().
ProcessManager::replace_process ($ pId, $ vars)
Updates or inserts a new process in the database, $vars is an asociative array containing the fields to update or to insert as needed. $pId is the processId
Definition at line 178 of file ProcessManager/ProcessManager.php.
References get_process().
Referenced by import_process(), and new_process_version().
ProcessManager::serialize_process ($ pId)
Creates an XML representation of a process.
Definition at line 50 of file src/ProcessManager/ProcessManager.php.
References get_process().
ProcessManager::unserialize_process ($ xml)
Creates a process from its XML representation
Definition at line 121 of file src/ProcessManager/ProcessManager.php.
The documentation for this class was generated from the following files:
ProcessManager/ProcessManager.php
src/ProcessManager/ProcessManager.php