<?php
// (c) Copyright 2002-2013 by authors of the Tiki Wiki CMS Groupware Project
//
// All Rights Reserved. See copyright.txt for details and a complete list of authors.
// Licensed under the GNU LESSER GENERAL PUBLIC LICENSE. See license.txt for details.
// $Id$

//this script may only be included - so its better to die if called directly.
if (strpos($_SERVER['SCRIPT_NAME'], basename(__FILE__)) !== false) {
	header('location: index.php');
	exit;
}

/**
 * Class Table_Code_Pager
 *
 * Creates code for the pager section of the Tablesorter code, including the code for ajax
 *
 * @package Tiki
 * @subpackage Table
 * @uses Table_Code_Manager
 */
class Table_Code_Pager extends Table_Code_Manager
{

	public function setCode()
	{
		global $prefs;
		$p = array();
		//add pager controls
		if ($this->pager) {
			$p[] = 'size: ' . $this->s['pager']['max'];
			$p[] = 'output: \'{startRow} to {endRow} ({totalRows})\'';
			$p[] = 'container: $(\'div#' . $this->s['pagercontrols']['id'] . '\')';
		}

		//ajax settings
		if ($this->ajax) {
			$p[] = 'ajaxObject: {dataType: \'html\'}';
			$p[] = 'ajaxUrl : \'' . $this->s['ajax']['url'] . '\'';

			//ajax processing - this part grabs the html, usually from the smarty template file
			$ap = array(
				'var parsed = $.parseHTML( data );',
				'var parsedtable = $(parsed).find(\'table#' . $this->id . ' tbody\');',
				'var data = $(parsedtable).html();',
				'$(table).find(\'tbody\').html( data );',
				'var total = \'' . $this->s['total'] . '\';',
				'return [ total ];'
			);
			$p[] = $this->iterate($ap, 'ajaxProcessing: function(data, table){', $this->nt2 . '}',
				$this->nt3, '', '');

			//customAjaxUrl: takes the url parameters generated by Tablesorter and converts to parameters that can
			//be used by Tiki
			$ca = array(
				'var vars = {}, hashes, hash, sort, sorts, filters, params = [], dir, newurl, offset = true;',
				'hashes = url.slice(url.indexOf(\'?\') + 1).split(\'&\');',
				'for(var i = 0; i < hashes.length; i++) {',
				'	hash = hashes[i].split(\'=\');',
				'	vars[hash[0]] = hash[1];',
				'}',
				'sort = ' . json_encode($this->s['ajax']['sort']) . ';',
				'filters = ' . json_encode($this->s['ajax']['filters']) . ';',
				'$.each(vars, function(key, value) {',
				'	if (key in sort) {',
				'		if (value == 0){',
				'			dir = \'_asc\';',
				'		} else {',
				'			dir = \'_desc\';',
				'		}',
				'		if (typeof sorts === \'undefined\') {',
				'			sorts = sort[key] + dir;',
				'		} else {',
				'			sorts += \',\' + sort[key] + dir;',
				'		}',
				'	}',
				'	if (key in filters) {',
				'		if (filters[key][value]){',
				'			params.push(filters[key][value]);',
				'		} else {',
				'			params.push(filters[key] + \'=\' + value);',
				'		}',
						'offset = false;',
				'	}',
				'});',
				'if (sorts) {',
				'	params.push(\'sort_mode=\' + sorts);',
				'}',
				'newurl = url.slice(0,url.indexOf(\'?\'));',
				'if (offset == false) {',
				'	offset = \'\';',
				'} else {',
				'	offset = \'&offset=\' + (this.page * this.size);',
				'}',
				'newurl = newurl + \'?numrows=\' + this.size + offset + \'&tsAjax=true\';',
				'$.each(params, function(key, value) {',
				'	newurl = newurl + \'&\' + value;',
				'});',
				'return newurl;'
			);
			$p[] = $this->iterate($ca, 'customAjaxUrl: function(table, url) {',  $this->nt2 . '}',
				$this->nt3, '', '');
		}
		if (count($p) > 0) {
			$code = $this->iterate($p, '.tablesorterPager({', $this->nt . '});', $this->nt2, '');
			parent::$code[self::$level1] = $code;
		}
	}
}