<?php
// (c) Copyright 2002-2015 by authors of the Tiki Wiki CMS Groupware Project
// 
// All Rights Reserved. See copyright.txt for details and a complete list of authors.
// Licensed under the GNU LESSER GENERAL PUBLIC LICENSE. See license.txt for details.
// $Id$

function wikiplugin_annotation_info()
{
	return array(
		'name' => tra('Image Annotation'),
		'documentation' => 'PluginAnnotation',
		'description' => tra('Annotate an image'),
		'prefs' => array('wikiplugin_annotation'),
		'body' => tra('Autogenerated content. Leave blank initially.'),
		'filter' => 'striptags',
		'iconname' => 'edit',
		'introduced' => 2,
		'tags' => array( 'basic' ),
		'format' => 'html',
		'params' => array(
			'src' => array(
				'required' => true,
				'name' => tra('Location'),
				'description' => tra('Absolute URL to the image or relative path from Tiki site root.'),
				'filter' => 'url',
				'default' => '',
				'since' => '3.0',
			),
			'width' => array(
				'required' => true,
				'name' => tra('Width'),
				'description' => tra('Image width in pixels.'),
				'filter' => 'digits',
				'default' => '',
				'since' => '3.0',
			),
			'height' => array(
				'required' => true,
				'name' => tra('Height'),
				'description' => tra('Image height in pixels.'),
				'filter' => 'digits',
				'default' => '',
				'since' => '3.0',
			),
			'align' => array(
				'required' => false,
				'name' => tra('Alignment'),
				'description' => tra('Image alignment.'),
				'filter' => 'alpha',
				'advanced' => true,
				'default' => 'left',
				'since' => '2.0',
				'options' => array(
					array('text' => '', 'value' => ''), 
					array('text' => tra('Left'), 'value' => 'left'), 
					array('text' => tra('Right'), 'value' => 'right'), 
					array('text' => tra('Center'), 'value' => 'center'), 
				),
			),
		)
	);
}

function wikiplugin_annotation($data, $params)
{
	global $page, $tiki_p_edit;
	$headerlib = TikiLib::lib('header');

	$params = array_merge(array( 'align' => 'left' ), $params);

	$annotations = array();
	foreach ( explode("\n", $data) as $line ) {
		$line = trim($line);
		if ( empty( $line ) )
			continue;

		if ( preg_match("/^\(\s*(\d+)\s*,\s*(\d+)\s*\)\s*,\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)(.*)\[(.*)\]$/", $line, $parts) ) {
			$parts = array_map('trim', $parts);
			list( $full, $x1, $y1, $x2, $y2, $label, $target ) = $parts;

			$annotations[] = array(
				'x1' => $x1,
				'y1' => $y1,
				'x2' => $x2,
				'y2' => $y2,
				'value' => $label,
				'target' => $target,
			);
		}
	}

	$annotations = json_encode($annotations);

	$headerlib->add_jsfile('lib/jquery_tiki/wikiplugin-annotation.js');

	static $uid = 0;
	$uid++;
	$cid = 'container-annotation-' . $uid;

	$labelSave = tra('Save changes to annotations');
	$message = tra('Image annotations changed.');
	
	if ( $tiki_p_edit == 'y' ) {
		$editableStr = tra('Editable');

		$form = <<<FORM
<form method="post" action="tiki-wikiplugin_edit.php">
	<div style="display:none">
		<input type="hidden" name="page" value="$page"/>
		<input type="hidden" name="type" value="annotation"/>
		<input type="hidden" name="index" value="$uid"/>
		<input type="hidden" name="message" value="$message"/>
		<textarea id="$cid-content" name="content"></textarea>
	</div>
	<div class="form-group">
		<input type="submit" class="btn btn-default btn-sm" value="$labelSave"/>
		<label>
			<input type="checkbox" id="$cid-editable">
			{$editableStr}
		</label>
	</div>
</form>
FORM;
	}
	else
		$form = '';

	// inititalise the annotations
	$headerlib->add_jq_onready('$("#' . $cid . '").imageAnnotation(' . $annotations . ');');

	$smarty = TikiLib::lib('smarty');
	$smarty->loadPlugin('smarty_function_icon');
	$minimize = smarty_function_icon(['name' => 'minimize'], $smarty);
	$delete = smarty_function_icon(['name' => 'delete'], $smarty);

	$labelStr = tra('Label');
	$linkStr = tra('Link');
	$saveStr = tra('Save');
	$closeStr = tra('Close');
	$removeStr = tra('Remove');

	if ($tiki_p_edit == 'y') {
		$editor_form = <<<EDITORFORM
		<div class="editor panel">
			<div class="panel-body">
				<form method="post" action="#" class="form-horizontal">
					<label class="form-group">
						<span class="col-sm-4">$labelStr</span>
						<input class="col-sm-8" type="text" name="label">
					</label>
					<label class="form-group">
						<span class="col-sm-4">$linkStr</span>
						<input class="col-sm-8" type="text" name="link">
					</label>
					<div class="form-group">
						<input type="submit" class="btn btn-default btn-sm" value="$saveStr">
						<a class="btn btn-default btn-sm minimize" href="#">$minimize $closeStr</a>
						<a class="btn btn-default btn-sm delete" href="#">$delete $removeStr</a>
					</div>
				</form>
			</div>
		</div>
EDITORFORM;
	} else {
		$editor_form = '';
	}

	return <<<ANNOTATION
<div class="wp-annotation">
	<div id="$cid" style="background:url({$params['src']}); width:{$params['width']}px; height:{$params['height']}px;">
{$editor_form}
	</div>
</div>
$form
ANNOTATION;
}
