<?php

// HAWIKI config file for Tikiwiki
// Last modified: 5. June 2005

define("HAWIKI_TITLE", "Tikiwiki");              // -> "title" of created HAWHAW deck
define("HAWIKI_MAXINPUTCHARS", 100000);          // maximum wiki size
define("HAWIKI_DISP_WIDTH",  300);               // HAWHAW display width (pixel)
define("HAWIKI_DISP_HEIGHT", 300);               //                height
define("HAWIKI_DISP_BGCOLOR", "#00BB77");        //                background color
define("HAWIKI_DATETIME_SHORT", "d/m/Y [H:i]");  // for modifications see PHP function date()
define("HAWIKI_DATETIME_LONG",  "l, F jS Y, g:i A");
define("HAWIKI_EXTLINK_ICON", "/img/icons/external_link"); // must exist as .gif and .wbmp version

?>
