<?php

// HAWIKI config file for TikiWiki
// Last modified: 8. November 2003

define("HAWIKI_TITLE", "TikiWiki");              // -> "title" of created HAWHAW deck
define("HAWIKI_MAXINPUTCHARS", 100000);          // maximum wiki size
define("HAWIKI_DISP_WIDTH",  300);               // HAWHAW display width (pixel)
define("HAWIKI_DISP_HEIGHT", 300);               //                height
define("HAWIKI_DISP_BGCOLOR", "#00BB77");        //                background color
define("HAWIKI_DATETIME_FORMAT", "d/m/Y [H:i]"); // for modifications see PHP function date()

?>
