<?php
require_once('tiki-setup.php');

if (!function_exists('ms_newMapObj')) {
	$smarty->assign('msg',tra("You must first setup MapServer"));
	$smarty->display("styles/$style_base/error.tpl");
	die;
}

$smarty->assign('mid','map/tiki-map.tpl');

if(@$feature_maps != 'y') {
  $smarty->assign('msg',tra("Feature disabled"));
  $smarty->display("styles/$style_base/error.tpl");
  die;
}

if (isset($_REQUEST['mapfile']))
{
  $mapfile = $_REQUEST['mapfile'];
} else
{
  $mapfile = $default_map;
}
$map = ms_newMapObj($map_path.$mapfile);
  
$layerbol=FALSE;
if (isset($_REQUEST['size']))
{
  $size=$_REQUEST['size'];
  $layerbol=TRUE;
} else
{
  $size=400;
}
$map->Set("width",$size);
$map->Set("height",$size);
$map->scalebar->Set("width",$size);

if (isset($_REQUEST['minx']) && isset($_REQUEST['miny'])
     && isset($_REQUEST['maxx']) && isset($_REQUEST['maxy']))
{
  $my_extent = ms_newrectObj();
  $my_extent->setextent($_REQUEST['minx'],$_REQUEST['miny'],$_REQUEST['maxx'],$_REQUEST['maxy']);
} else
{
  $my_extent = ms_newrectObj();
  $my_extent->setextent($map->extent->minx,$map->extent->miny,$map->extent->maxx,$map->extent->maxy);
}
$query=FALSE;
$map_querymsg='<table border="1" >';
if (isset($_REQUEST['zoom']))
{
  $zoom=$_REQUEST['zoom'];
  $my_point = ms_newpointObj();
  if (isset($_REQUEST['x']) && isset($_REQUEST['y']) && $zoom!=0)
  {
    $my_point->setXY($_REQUEST['x'],$_REQUEST['y']);
  } else
  {
    $my_point->setXY(($map->height)/2,($map->width)/2);
  }
  if ($zoom==0)  // It is a query
  {
    $map->zoompoint(1,$my_point,$map->width,$map->height,$my_extent);
    if (isset($_REQUEST['x']) && isset($_REQUEST['y']))
    {
      //get the real world coordinates
      $x=$_REQUEST['x'];
      $y=$_REQUEST['y'];
      $width=$map->width-1;
      $height=$map->height-1;
      $minx=$map->extent->minx;
      $maxx=$map->extent->maxx;
      $miny=$map->extent->miny;
      $maxy=$map->extent->maxy;
      $dx=$maxx-$minx;
      $dy=$maxy-$miny;
      $factorx=$dx/$width;
      $factory=$dy/$height;
      $corx=$x*$factorx+$minx;
      $cory=$maxy-$y*$factory;
      $query_point= ms_newpointObj();
      $query_point->setXY($corx,$cory);
      $map_querymsg.='<tr><td colspan="2">'.tra('Query point:').' <b>'.$corx.' / '.$cory.'</b></td><tr>';
      $query=TRUE;
    }    
  } else
  {
    $map->zoompoint($zoom,$my_point,$map->width,$map->height,$my_extent);
  }
} else
{
  $zoom=1;
}



//define which layer is visible
for ($j=0;$j<$map->numlayers;$j++)
{
  $my_layer=$map->getLayer($j);
  if (isset($_REQUEST[str_replace(" ","_",$my_layer->name)]))
  {
    if ($_REQUEST[str_replace(" ","_",$my_layer->name)]==1)
    {
      $my_layer->Set("status",MS_ON);
    }
  } else
  {
    // test to see if we are not on the first drawing
    if ($layerbol)
    {
    	$my_layer->Set("status",MS_OFF);
    }
  }
  //Display labels
  if ($my_layer->labelitem!="")
  {
  		$layer_label[$j]="On";
  		if (isset($_REQUEST[str_replace(" ","_",$my_layer->name)."_label"]))
    {
  		  $my_layers_label_checked[$j]="checked";
  		} else
  		{
  		  $my_layers_label_checked[$j]="";
  		  $my_layer->Set("labelmaxscale",0);
  		}
  } else
  {
    $layer_label[$j]="Off";
  }
  if ($query) // We have a query
  {
    if (@$my_layer->queryByPoint($query_point,MS_MULTIPLE,0)==MS_SUCCESS)
    {
      $my_layer->open();
      $map_querymsg.='<tr><td colspan="2">'.tra('layer:').' <b>'.$my_layer->name.'</b></td></tr>';
      for($k=0;$k<$my_layer->getNumResults();$k++)
      {       
        $my_resultcache=$my_layer->getResult($k);
        $my_shape=$my_layer->getShape($my_resultcache->tileindex,$my_resultcache->shapeindex);
        $my_array=$my_shape->values;
        $map_querymsg.='<tr><td colspan="2"><small>'.tra('Record:').' '.$my_resultcache->shapeindex.'</small></td></tr>';
        foreach ($my_array as $key => $value)
        {
          $map_querymsg.='<tr><td><small>'.$key.'</small></td><td><small>'.$value.'</small></td></tr>';
        }
      }
      $my_layer->close();
    }   
  }
}  
$map_querymsg.="</table>";
$smarty->assign('map_querymsg',$map_querymsg);

$image = $map->drawquery();
$image_url = $image->saveWebImage();
$image_ref = $map->drawReferenceMap();
$image_ref_url = $image_ref->saveWebImage();
$image_leg = $map->drawLegend();
$image_leg_url = $image_leg->saveWebImage();
$image_scale = $map->drawScaleBar();
$image_scale_url = $image_scale->saveWebImage();

$minx=$map->extent->minx;
$miny=$map->extent->miny;
$maxx=$map->extent->maxx;
$maxy=$map->extent->maxy;

$smarty->assign('mapfile',$mapfile);

$smarty->assign('image_url',$image_url);
$smarty->assign('image_ref_url',$image_ref_url);
$smarty->assign('image_leg_url',$image_leg_url);
$smarty->assign('image_scale_url',$image_scale_url);
$smarty->assign('minx',$minx);
$smarty->assign('miny',$miny);
$smarty->assign('maxx',$maxx);
$smarty->assign('maxy',$maxy);

$smarty->assign('size',$size);
$smarty->assign('possiblesizes',array(200,400,600));
$smarty->assign('displaysizes',array('200x200','400x400','600x600'));

$smarty->assign_by_ref('layer_label',$layer_label);
$smarty->assign_by_ref('my_layers_label_checked',$my_layers_label_checked);

// is the user registered?
if(isset($_REQUEST['view_user'])) {
  $userwatch = $_REQUEST['view_user'];
} else {
  if($user) {
    $userwatch = $user;
  } else {
			$userwatch ="";
  }
}  

  for ($j=0;$j<$map->numlayers;$j++)
  {
    $my_layers[$j]=$map->getLayer($j);
      
    //Metadata handling
    $link=$my_layers[$j]->getMetadata("WIKI");
    if ($link!="")
    {
      if($tikilib->page_exists($link))
      {
        $layer_wiki[$j]='<a href="tiki-index.php?page='.$link.'"><small>'.$my_layers[$j]->name.'</small></a>';
      } else
      {
        $layer_wiki[$j]='<small>'.$my_layers[$j]->name.'<a href="tiki-editpage.php?page='.$link.'">?</a></small>';
      }
    } else
    {
      $layer_wiki[$j]='<small>'.$my_layers[$j]->name.'</small>';
    }
    if ($userwatch!="")
    {
      $layer_download[$j]=$my_layers[$j]->getMetadata("DOWNLOAD");
    } else
    {
    	$layer_download[$j]="";
    }
  
    //Layer display Handling
    if ($my_layers[$j]->status==MS_ON)
    {
      $my_layers_checked[$j]="checked";
      $bolcheck=1;
    } else
    {
      $my_layers_checked[$j]="";
      $bolcheck=0;
    }
  }

$smarty->assign_by_ref('my_layers',$my_layers);
$smarty->assign_by_ref('my_layers_checked',$my_layers_checked);
$smarty->assign_by_ref('layer_wiki',$layer_wiki);
$smarty->assign_by_ref('layer_download',$layer_download);
$smarty->assign('userwatch',$userwatch);

  for ($i=-4;$i<=4;$i++)
  {
     
  	  switch($i)
  	  {
  	  case "-4":
  	  case "-3":
  	  case "-2":
  	    $zoom_values[]=$i;
  	    $zoom_display[]='zoom out '.$i.'x';
		    break;
		  case "0":
		    $zoom_values[]=$i;
		    $zoom_display[]='query';
       break;
		  case "1":
		    $zoom_values[]=$i;
		    $zoom_display[]='pan';
       break;
  	  case "2":
  	  case "3":
  	  case "4":
  	    $zoom_values[]=$i;
  	    $zoom_display[]='zoom in '.$i.'x';
       break;
		  }
		}
$smarty->assign('zoom',$zoom);		
$smarty->assign_by_ref('zoom_values',$zoom_values);
$smarty->assign_by_ref('zoom_display',$zoom_display);

$smarty->display('tiki.tpl');
?>
