<?php

$tikiId = "TikiWiki"; // TODO: make configurable and add version number 

$rss_use_css = false; // default is: do not use css
if (isset($_REQUEST["css"])) {
	$rss_use_css = true;
}

$rss_version = 1; // default is: rss v1.0 - TODO: make this configurable
if (isset($_REQUEST["ver"]))
	if (substr($_REQUEST["ver"],0,1) == '2') {
		$rss_version = 2;
	}

$url = $_SERVER["REQUEST_URI"];
$url = substr($url, 0, strpos($url."?", "?")); // strip all parameters from url
$urlarray = parse_url($url);

$pagename = substr($urlarray["path"], strrpos($urlarray["path"], '/') + 1);

$home = htmlspecialchars(httpPrefix().str_replace($pagename, $tikiIndex, $urlarray["path"]));
$img = htmlspecialchars(httpPrefix().str_replace($pagename, "img/tiki.jpg", $urlarray["path"]));
$read = httpPrefix().str_replace($pagename, "$readrepl", $urlarray["path"]);

$url = htmlspecialchars(httpPrefix().$url);
$title = htmlspecialchars($title);
$desc = htmlspecialchars($desc);
$url = htmlspecialchars($url);
$css = htmlspecialchars(httpPrefix().str_replace($pagename, "lib/rss/rss-style.css", $urlarray["path"]));

// --- output starts here 
header("content-type: text/xml");
print '<?xml version="1.0" encoding="UTF-8" ?>'."\n";
print '<!--  RSS generated by TikiWiki CMS (www.tikiwiki.org) on '.date('r').' -->'."\n";

if ($rss_use_css) {
	print '<?xml-stylesheet href="'.$css.'" type="text/css"?>'."\n";
}

if ($rss_version > 1) {
	print '<rss version="2.0">'."\n";
	print "<channel>\n";
} else {
	print '<rdf:RDF xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/">'."\n";
	print '<channel rdf:about="'.$url.'">'."\n";
}

print "<title>".$title."</title>\n";
print "<link>".$home."</link>\n";
print "<description>".$desc."</description>\n";

if ($rss_version < 2) {
	print "<dc:language>en-us</dc:language>\n"; // TODO: make configurable
  // print "<dc:publisher> company </dc:publisher>\n"; // TODO: make configurable
  // print "<dc:creator>name@host.com (name)</dc:creator>\n"; // TODO: make configurable
}
else
{
	print "<language>en-us</language>\n"; // TODO: make configurable
	print "<docs>http://backend.userland.com/rss</docs>\n";
	print "<generator>$tikiId</generator>\n";
	// print "<category domain=""></category>\n";
  // print "<managingEditor>@. (name)</managingEditor>\n"; // TODO: make configurable
  // print "<webMaster>@. (name)</webMaster>\n"; // TODO: make configurable
}

print "\n";

if ($rss_version < 2) {
	print "<items>\n";
	print "<rdf:Seq>\n";
	// LOOP collecting last changes (index)
	foreach ($changes["data"] as $chg) {
		$resource=$read.$chg["$id"];
		if ($id == "blodId") { $resource .= "&postId=".$chg["postId"]; }
		$resource = htmlspecialchars($resource);		
		print ('        <rdf:li rdf:resource="'.$resource.'" />'."\n");
	}
	print "</rdf:Seq>\n";
	print "</items>\n";
	if ($rss_version < 2) {
		print '<image rdf:resource="'.$img.'" />'."\n";
	}
	print "</channel>\n\n";
}

if ($rss_version < 2) {
	print '<image rdf:about="'.$img.'">'."\n";
}
else
{
	print '<image>'."\n";
}
print "<title>".$title."</title>\n";
print "<link>".$home."</link>\n";
print "<url>".$url."</url>\n";
print "</image>\n\n";

// LOOP collecting last changes to image galleries
foreach ($changes["data"] as $chg) {
  $date = htmlspecialchars(gmdate('D, d M Y H:i:s T', $chg["$dateId"]));
  
	$about = $read.$chg["$id"];
	// blogs have posts, add those to the url:
	if ($id == "blogId") { $about .= "&postId=".$chg["postId"]; }		
  $about = htmlspecialchars($about);

  $title = $chg["$titleId"];
	// titles for blogs are dates, so make them readable:
	if ($titleId == "created") { $title = gmdate('D, d M Y H:i:s T', $title); }		
  $title = htmlspecialchars($title);

  $description = htmlspecialchars($chg["$descId"]);

	if ($rss_version < 2) {
		print ('<item rdf:about="'.$about.'">'."\n");
	} else {
		print ("<item>\n");
	}
	print ('  <title>'.$title.'</title>'."\n");
	print ('  <link>'.$about.'</link>'."\n");

	if ($rss_version < 2) {
		print ('  <description>'.$description.'</description>'."\n");
		print ("  <dc:date>".$date."</dc:date>\n");
	}
	else
	{		
		print ('<description>'.$description.'</description>'."\n");
		// print("<author>".htmlspecialchars($chg["user"])."</author>\n"); // TODO: email address of author
		print ('<guid isPermaLink="true">'.$about.'</guid>'."\n");
		print ("<pubDate>".$date."</pubDate>\n");
	}
	print ('</item>'."\n\n");
}

if ($rss_version < 2)
{
	print "</rdf:RDF>\n";
} else {
	print "</channel>\n";
	print "</rss>\n";
}

?>