<a href="javascript:insertAt('{$area_name}','(:biggrin:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_biggrin.gif" alt="{tr}big grin{/tr}" title="{tr}big grin{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:confused:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_confused.gif" alt="{tr}confused{/tr}" title="{tr}confused{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:cool:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_cool.gif" alt="{tr}cool{/tr}" title="{tr}cool{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:cry:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_cry.gif" alt="{tr}cry{/tr}" title="{tr}cry{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:eek:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_eek.gif" alt="{tr}eek{/tr}" title="{tr}eek{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:evil:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_evil.gif" alt="{tr}evil{/tr}" title="{tr}evil{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:exclaim:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_exclaim.gif" alt="{tr}exclaim{/tr}" title="{tr}exclaim{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:frown:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_frown.gif" alt="{tr}frown{/tr}" title="{tr}frown{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:idea:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_idea.gif" alt="{tr}idea{/tr}" title="{tr}idea{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:lol:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_lol.gif" alt="{tr}lol{/tr}" title="{tr}lol{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:mad:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_mad.gif" alt="{tr}mad{/tr}" title="{tr}mad{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:mrgreen:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_mrgreen.gif" alt="{tr}mr green{/tr}" title="{tr}mr green{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:neutral:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_neutral.gif" alt="{tr}neutral{/tr}" title="{tr}neutral{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:question:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_question.gif" alt="{tr}question{/tr}" title="{tr}question{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:razz:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_razz.gif" alt="{tr}razz{/tr}" title="{tr}razz{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:redface:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_redface.gif" alt="{tr}redface{/tr}" title="{tr}redface{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:rolleyes:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_rolleyes.gif" alt="{tr}rolleyes{/tr}" title="{tr}rolleyes{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:sad:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_sad.gif" alt="{tr}sad{/tr}" title="{tr}sad{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:smile:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_smile.gif" alt="{tr}smile{/tr}" title="{tr}smile{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:surprised:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_surprised.gif" alt="{tr}surprised{/tr}" title="{tr}surprised{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:twisted:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_twisted.gif" alt="{tr}twisted{/tr}" title="{tr}twisted{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:wink:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_wink.gif" alt="{tr}wink{/tr}" title="{tr}wink{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:arrow:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_arrow.gif" alt="{tr}arrow{/tr}" title="{tr}arrow{/tr}" border="0" width="15" height="15" /></a>
<a href="javascript:insertAt('{$area_name}','(:santa:)');" onclick="needToConfirm = false;"><img src="img/smiles/icon_santa.gif" alt="{tr}santa{/tr}" title="{tr}santa{/tr}" border="0" width="15" height="15" /></a>
